# Generated by Django 3.1.4 on 2021-02-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Indian Cuisine', 'Indian Cuisine'), ('Italian Cuisine', 'Italian Cuisine')], max_length=100, null=True)),
                ('food_type', models.CharField(choices=[('Sweet', 'Sweet'), ('Spicy', 'Spicy')], max_length=100, null=True)),
            ],
        ),
    ]
